### ISSUE TITLE
Create a baseline for score

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/hackathon#13]
Keep a `baseline.json` with baseline scores for Tailcall. We can use them to normalize the results and print the actual score.

The `baseline.json` is updated with tailcall scores based on the Tailcall PRs. Looks like this 

```jsonc
{
  "posts-nested": 100,
  "posts-title": 2000,
  "posts-with-user": 300
}
```

**Comment by meskill** [comment]
baseline is generated now https://github.com/tailcallhq/hackathon/blob/main/reference/results/stats.json with the help of generated job https://github.com/tailcallhq/hackathon/actions/runs/10799013534/job/29953791457 that could be rerun manually if needed
