### ISSUE TITLE
comment the benchmark numbers on the PR

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/hackathon#14]
Once someone creates a PR, we need to run the benchmarks and comment on the commit 

1. The benchmark numbers
2. Overall score of the run based on [baseline.json](https://github.com/tailcallhq/hackathon/issues/13)

**Comment by meskill** [comment]
the comment for pr is implemented https://github.com/tailcallhq/hackathon/pull/25#issuecomment-2341959987
