### ISSUE TITLE
Users should not be allowed to change CI settings

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/hackathon#15]
Ensure the CI is running wrt to main so that developers don't customize CI in anyway, this will eventually become a problem for us where people just modifying tests and making them pass.

The developers are free to customize `run.sh` to setup their env.

**Comment by meskill** [comment]
I've updated the ci job in https://github.com/tailcallhq/hackathon/commit/911801547a81049e6ca66a21435488a175b36c1c to check the changes in non project files.
The changes in ci is a different story - I think changes in it should be approved by collaborator every time so we'll see the issues before running ci
